# Controls how GitHub's "Generate release notes" button groups merged PRs.
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - question
  categories:
    - title: ✨ Features
      labels:
        - enhancement
    - title: 🐛 Fixes
      labels:
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🔧 Maintenance
      labels:
        - dependencies
        - github_actions
    - title: Other changes
      labels:
        - "*"
