displayName=Better Monster Examine
author=prettyrocket
description=Search any monster and view its full wiki-style combat stats
tags=npc,stats,examine,search,defensive,weakness,elemental,bestiary,monster,wiki,dps
plugins=com.bettermonsterexamine.BetterMonsterExaminePlugin
build=standard
